version: '2'
services:
    app:
        container_name: {{cookiecutter.project_slug}}_app
        build: .
        command: bash -c "source ~/.venvs/{{cookiecutter.project_slug}}venv/bin/activate && uwsgi --http :8000 --module {{cookiecutter.project_slug}}.run --socket :8001" 
        env_file:
            - production.env
        environment:
            - PYTHONUNBUFFERED=1
            - PRODUCTION
        volumes:
            - .:/code
        ports:
            - "8000:8000"
            - "8001:8001"

    server:
        container_name: {{cookiecutter.project_slug}}_server
        build: .dockerfiles/nginx
        ports:
            - "80:80"
        depends_on:
            - app
